# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Garment-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Garment-iOS
  pod 'RealmSwift'
  
  target 'Garment-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Garment-iOSUITests' do
    # Pods for testing
  end

end
